name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec biome ci .
      - run: terraform fmt -check -recursive
      - run: |
          terraform -chdir=infra init -backend=false
          terraform -chdir=infra validate
      - run: actionlint
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
      - run: gitleaks git --redact --verbose --log-opts="${FROM}..${TO}"
        env:
          FROM: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          TO: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
